	NIOSII_WEEK3 u0 (
		.accel_I2C_SDAT        (<connected-to-accel_I2C_SDAT>),        //          accel.I2C_SDAT
		.accel_I2C_SCLK        (<connected-to-accel_I2C_SCLK>),        //               .I2C_SCLK
		.accel_G_SENSOR_CS_N   (<connected-to-accel_G_SENSOR_CS_N>),   //               .G_SENSOR_CS_N
		.accel_G_SENSOR_INT    (<connected-to-accel_G_SENSOR_INT>),    //               .G_SENSOR_INT
		.camera_ready_export   (<connected-to-camera_ready_export>),   //   camera_ready.export
		.clk_clk               (<connected-to-clk_clk>),               //            clk.clk
		.dram_addr             (<connected-to-dram_addr>),             //           dram.addr
		.dram_ba               (<connected-to-dram_ba>),               //               .ba
		.dram_cas_n            (<connected-to-dram_cas_n>),            //               .cas_n
		.dram_cke              (<connected-to-dram_cke>),              //               .cke
		.dram_cs_n             (<connected-to-dram_cs_n>),             //               .cs_n
		.dram_dq               (<connected-to-dram_dq>),               //               .dq
		.dram_dqm              (<connected-to-dram_dqm>),              //               .dqm
		.dram_ras_n            (<connected-to-dram_ras_n>),            //               .ras_n
		.dram_we_n             (<connected-to-dram_we_n>),             //               .we_n
		.esp_data_ready_export (<connected-to-esp_data_ready_export>), // esp_data_ready.export
		.gpio_export           (<connected-to-gpio_export>),           //           gpio.export
		.hex0_export           (<connected-to-hex0_export>),           //           hex0.export
		.hex1_export           (<connected-to-hex1_export>),           //           hex1.export
		.hex2_export           (<connected-to-hex2_export>),           //           hex2.export
		.hex3_export           (<connected-to-hex3_export>),           //           hex3.export
		.hex4_export           (<connected-to-hex4_export>),           //           hex4.export
		.hex5_export           (<connected-to-hex5_export>),           //           hex5.export
		.img_addr_export       (<connected-to-img_addr_export>),       //       img_addr.export
		.led_export            (<connected-to-led_export>),            //            led.export
		.led_module_export     (<connected-to-led_module_export>),     //     led_module.export
		.pb_export             (<connected-to-pb_export>),             //             pb.export
		.pixeldata_export      (<connected-to-pixeldata_export>),      //      pixeldata.export
		.speaker_export        (<connected-to-speaker_export>),        //        speaker.export
		.spi_MISO              (<connected-to-spi_MISO>),              //            spi.MISO
		.spi_MOSI              (<connected-to-spi_MOSI>),              //               .MOSI
		.spi_SCLK              (<connected-to-spi_SCLK>),              //               .SCLK
		.spi_SS_n              (<connected-to-spi_SS_n>),              //               .SS_n
		.spi_select_export     (<connected-to-spi_select_export>),     //     spi_select.export
		.sw_export             (<connected-to-sw_export>),             //             sw.export
		.wren_export           (<connected-to-wren_export>)            //           wren.export
	);

