#include "soundeffects.h"
#include "control.h"

#include <stdint.h>
#include <stdlib.h>

#include "system.h"
#include "io.h"
#include "altera_avalon_pio_regs.h"

/*
   RTOS-only game SFX test version.

   This file intentionally avoids alt_busy_sleep() / software busy-wait audio.
   Each tone is generated by toggling the speaker using OSTimeGet() timing and
   yielding with OSTimeDly(1), so other RTOS tasks can run during sound playback.

   Limitation:
   The tone resolution is limited by OS_TICKS_PER_SEC. If OS_TICKS_PER_SEC is 100,
   the highest clean square-wave tone is roughly 50 Hz. If it is 1000, it is roughly
   500 Hz. High musical values such as 1046 Hz, 2094 Hz, etc. are clamped by the
   RTOS tick rate and may sound lower/choppier than the original busy-wait version.
*/

#ifndef OS_TICKS_PER_SEC
#define OS_TICKS_PER_SEC 100u
#endif

#define SFX_RTOS_MIN_HALF_TICKS 1u
#define SFX_RTOS_YIELD_TICKS    1u

extern volatile int GPIO_state;

void sound_init(void)
{
    play_speaker(0, 0);
    IOWR_ALTERA_AVALON_PIO_DATA(PIO_SPEAKER_BASE, 0);
}

static uint32_t ms_to_ticks(uint32_t ms)
{
    uint32_t ticks = (uint32_t)(((uint64_t)ms * (uint64_t)OS_TICKS_PER_SEC + 999u) / 1000u);
    return (ticks == 0u) ? 1u : ticks;
}

static uint32_t us_to_ticks(uint32_t us)
{
    uint32_t ticks = (uint32_t)(((uint64_t)us * (uint64_t)OS_TICKS_PER_SEC + 999999u) / 1000000u);
    return (ticks == 0u) ? 1u : ticks;
}

static uint32_t half_period_ticks_for_freq(int frequency)
{
    uint32_t half_period_us;
    uint32_t ticks;

    if (frequency <= 0) {
        return 0u;
    }

    half_period_us = (uint32_t)(500000u / (uint32_t)frequency);
    if (half_period_us == 0u) {
        half_period_us = 1u;
    }

    ticks = us_to_ticks(half_period_us);
    if (ticks < SFX_RTOS_MIN_HALF_TICKS) {
        ticks = SFX_RTOS_MIN_HALF_TICKS;
    }

    return ticks;
}

static void speaker_force_off(void)
{
    play_speaker(0, 0);
    IOWR_ALTERA_AVALON_PIO_DATA(PIO_SPEAKER_BASE, 0);
}

static void play_tone_rtos(int frequency, uint32_t duration_us)
{
    uint32_t duration_ticks;
    uint32_t start_tick;
    uint32_t last_toggle_tick;
    uint32_t half_ticks;
    int level = 0;

    if (frequency <= 0 || duration_us == 0u) {
        speaker_force_off();
        return;
    }

    duration_ticks = us_to_ticks(duration_us);
    half_ticks = half_period_ticks_for_freq(frequency);
    if (half_ticks == 0u) {
        speaker_force_off();
        return;
    }

    start_tick = (uint32_t)OSTimeGet();
    last_toggle_tick = start_tick;

    while ((uint32_t)((uint32_t)OSTimeGet() - start_tick) < duration_ticks) {
        uint32_t now = (uint32_t)OSTimeGet();

        if ((uint32_t)(now - last_toggle_tick) >= half_ticks) {
            last_toggle_tick = now;
            level = !level;
            IOWR_ALTERA_AVALON_PIO_DATA(PIO_SPEAKER_BASE, level ? 1 : 0);
        }

        OSTimeDly(SFX_RTOS_YIELD_TICKS);
    }

    speaker_force_off();
}

static void silence_rtos(uint32_t duration_us)
{
    uint32_t ticks = us_to_ticks(duration_us);
    speaker_force_off();
    OSTimeDly(ticks);
}

void sfx_laser_shoot(void)
{
    int freq;
    for (freq = 2500; freq > 500; freq -= 250) {
        play_tone_rtos(freq, 12000u);
    }
    speaker_force_off();
}

void sfx_explosion(void)
{
    int i;
    int rumble;


	#ifdef PIO_GPIO_BASE
		GPIO_state = GPIO_state | 0x1;
		IOWR_ALTERA_AVALON_PIO_DATA(PIO_GPIO_BASE, GPIO_state);
	#endif

    for (i = 0; i < 8; i++) {
        int noise_freq = 120 + (rand() % 520);
        uint32_t step_duration = 18000u + (uint32_t)(rand() % 18000);
        play_tone_rtos(noise_freq, step_duration);
    }

    for (rumble = 220; rumble > 70; rumble -= 30) {
        play_tone_rtos(rumble, 20000u);
    }

    speaker_force_off();

	#ifdef PIO_GPIO_BASE
		GPIO_state = GPIO_state & ~0x1;
		IOWR_ALTERA_AVALON_PIO_DATA(PIO_GPIO_BASE, GPIO_state);
	#endif
}

void sfx_portal(void)
{
    play_tone_rtos(220, 60000u);
    play_tone_rtos(330, 60000u);
    play_tone_rtos(440, 60000u);
    play_tone_rtos(330, 60000u);
    speaker_force_off();
}

void sfx_menu_blip(void)
{
    play_tone_rtos(300, 50000u);
    speaker_force_off();
}

void sfx_error_buzz(void)
{
    play_tone_rtos(120, 80000u);
    silence_rtos(30000u);
    play_tone_rtos(120, 100000u);
    speaker_force_off();
}

void sfx_eat_apple(void)
{
    play_tone_rtos(220, 50000u);
    play_tone_rtos(330, 60000u);
    speaker_force_off();
}

void sfx_end_screen(void)
{
    play_tone_rtos(196, 80000u);
    play_tone_rtos(247, 80000u);
    play_tone_rtos(330, 100000u);
    silence_rtos(50000u);
    play_tone_rtos(330, 90000u);
    speaker_force_off();
}

void sfx_change(void)
{
    play_tone_rtos(260, 60000u);
    speaker_force_off();
}

void sfx_click(void)
{
    play_tone_rtos(320, 25000u);
    speaker_force_off();
}

void sfx_snake_turn(void)
{
    play_tone_rtos(260, 35000u);
    speaker_force_off();
}

void sfx_clear(void)
{
    play_tone_rtos(220, 60000u);
    play_tone_rtos(150, 60000u);
    play_tone_rtos(90, 90000u);
    speaker_force_off();
}

void sfx_enter_snake(void)
{
    play_tone_rtos(120, 180000u);
    play_tone_rtos(160, 180000u);
    play_tone_rtos(220, 220000u);
    silence_rtos(60000u);
    play_tone_rtos(260, 240000u);
    play_tone_rtos(320, 300000u);
    silence_rtos(80000u);
    play_tone_rtos(220, 250000u);
    play_tone_rtos(300, 300000u);
    silence_rtos(100000u);
    play_tone_rtos(360, 350000u);
    speaker_force_off();
}

void sfx_enter_draw(void)
{
    play_tone_rtos(90, 160000u);
    play_tone_rtos(140, 180000u);
    play_tone_rtos(190, 180000u);
    play_tone_rtos(240, 220000u);
    silence_rtos(70000u);
    play_tone_rtos(300, 250000u);
    play_tone_rtos(360, 300000u);
    silence_rtos(80000u);
    play_tone_rtos(240, 250000u);
    play_tone_rtos(180, 260000u);
    silence_rtos(100000u);
    play_tone_rtos(320, 350000u);
    speaker_force_off();
}

void sfx_enter_battle(void)
{
    play_tone_rtos(80, 220000u);
    silence_rtos(60000u);
    play_tone_rtos(110, 220000u);
    silence_rtos(60000u);
    play_tone_rtos(150, 260000u);
    play_tone_rtos(200, 320000u);
    silence_rtos(120000u);
    play_tone_rtos(130, 300000u);
    play_tone_rtos(180, 380000u);
    silence_rtos(100000u);
    play_tone_rtos(90, 350000u);
    speaker_force_off();
}

